import { Platform, StatusBar } from "react-native";

const variaveis = {
  versao: '1.0.1',
  urlPDF: 'https://www.aplicativomaisescola.online/',
  urlAPI: 'https://www.aplicativomaisescola.online/api/',  
  primaryColor: '#20418b',
  secondaryColor: '#1db6e6',
  primaryTextColor: '#FFF',
  secondaryTextColor: '#b3e8ef',
  placeholderTextColor: '#A9A9A9',
  STATUSBAR_HEIGHT: Platform.OS === 'ios' ? 48 : StatusBar.currentHeight,
  bloqueadas: [
    {codigo: '202', nome: 'Hora do Saber'},
    {codigo: '20048', nome: 'Unamea'},
    {codigo: '20039', nome: 'Santa Emília'},
    {codigo: '60025', nome: 'União Tenoné'},
    {codigo: '20022', nome: 'Betel'},
    {codigo: '20030', nome: 'Universo'},
    {codigo: '60033', nome: 'CIPP'},
    {codigo: '60007', nome: 'CEMI'},
    {codigo: '60006', nome: 'PAULISTA'},
    {codigo: '60011', nome: 'CEI'},
    {codigo: '20037', nome: 'FILADELFIA'},
    {codigo: '22007', nome: 'MUNDO DO SABER'},
    {codigo: '23003', nome: 'SEMEADOR'},
    {codigo: '23006', nome: 'MANAHIN'},
    {codigo: '60056', nome: 'INOVE'},
  ],
  controledeacesso: [
    {codigo: '20052', nome: 'Gilmar Lucena'},
    {codigo: '20020', nome: 'Novo Horizonte'},
    {codigo: '60056', nome: 'Inove Escola'},
  ],
  diassemana: [
    'Domingo',
    'Segunda-Feira',
    'Terça-Feira',
    'Quarta-Feira',
    'Quinta-Feira',
    'Sexta-Feira',
    'Sábado',
  ],
  meses: [
    { mes: 1, mes_: '01', des: 'Janeiro' },
    { mes: 2, mes_: '02', des: 'Fevereiro' },
    { mes: 3, mes_: '03', des: 'Março' },
    { mes: 4, mes_: '04', des: 'Abril' },
    { mes: 5, mes_: '05', des: 'Maio' },
    { mes: 6, mes_: '06', des: 'Junho' },
    { mes: 7, mes_: '07', des: 'Julho' },
    { mes: 8, mes_: '08', des: 'Agosto' },
    { mes: 9, mes_: '09', des: 'Setembro' },
    { mes: 10, mes_: '10', des: 'Outubro' },
    { mes: 11, mes_: '11', des: 'Novembro' },
    { mes: 12, mes_: '12', des: 'Dezembro' },
],
};

export default variaveis;
